### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by criszalo1997** [CodeDredd/laravel-soap#38]
Good greetings I am new and using your library I have a problem when using authentication, I would like to know what middleware uses for authentication on the routes since I use the default auth does not authenticate.

So I use the authentication.
`        $response = Soap::baseWsdl("$this->serverUrl/$this->serverScript?wsdl")
        ->withBasicAuth('test','123')
        ->LoguearUsuario($data);
`

middleware on the route.
`Route::get('user', function () {
     return "hello user";
})->middleware('auth');`

**Comment by lostdesign** [comment]
That authentication is mainly meant for authenticating against the SOAP API and not to be used as a authentication layer for your app. If you want to use the authentication through the SOAP API, you'd need to write a custom auth middleware.

At least that's my guess, working with that library.

**Comment by criszalo1997** [comment]
ok thanks for the prompt response i am new to the implementation of laravel i dont know if it is possible that you can give me an example, i would appreciate it

**Comment by CodeDredd** [comment]
As @lostdesign mentioned the authentications are against the soap api. Behind i am using the middlewares from https://github.com/phpro/soap-client/blob/master/docs/middlewares.md. Laravel auth system is for your appication authentication.
Maybe you can give my some more details, so that i can provide you an example for you usecase.

**Comment by CodeDredd** [comment]
seems to be resolved
